apiVersion: v1
kind: Service
metadata:
  name: {{ include "jackdevops.name" . }}-web
  labels:
    {{- include "jackdevops.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.web.port }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "jackdevops.name" . }}
    app.kubernetes.io/component: web
